fix key-manager.py local variable 'crypto_ctx' referenced before assignment
2023-01-31 11:55:22 ERR key-manager.py:471 unhandled exception in getkey0
Traceback (most recent call last):
  File "/home/bac/workspace/bee/regress/bin/key-manager.py", line 469, in getkey
    getkey0(args)
  File "/home/bac/workspace/bee/regress/bin/key-manager.py", line 409, in getkey0
    crypto_ctx=get_crypto_ctx_from_config(args, volume_name)
  File "/home/bac/workspace/bee/regress/bin/key-manager.py", line 310, in get_crypto_ctx_from_config
    return crypto_ctx
UnboundLocalError: local variable 'crypto_ctx' referenced before assignment